replicaCount: 2

image:
  repository: ekart/shoppingkart
  pullPolicy: IfNotPresent
  tag: "1"

service:
  type: LoadBalancer
  port: 8070

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  hosts:
    - host: your-hostname
      paths:
        - path: /
          pathType: Prefix
  tls: []
